#
#	GNUmakefile
#
#	Makefile for the PrefsModule framework
#
#	Copyright (C) 2002 Jeff Teunissen <deek@d2dc.net>
#
#	This Makefile is free software; you can redistribute it and/or
#	modify it under the terms of the GNU Lesser General Public License
#	as published by the Free Software Foundation; either version 2.1
#	of the License, or (at your option) any later version.
#
#	This framework is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
#	See the GNU Lesser General Public License for more details.
#
#	You should have received a copy of the GNU Lesser General Public
#	License along with this framework; if not, write to:
#
#		Free Software Foundation, Inc.
#		59 Temple Place - Suite 330
#		Boston, MA  02111-1307, USA
#
#	$Id$

include $(GNUSTEP_MAKEFILES)/common.make

FRAMEWORK_NAME=		PrefsModule

PrefsModule_HEADER_FILES= \
	PrefsModule.h

PrefsModule_CURRENT_VERSION_NAME=1.2.0
PrefsModule_DEPLOY_WITH_CURRENT_VERSION=yes

-include GNUmakefile.preamble
-include GNUmakefile.local

include $(GNUSTEP_MAKEFILES)/aggregate.make
include $(GNUSTEP_MAKEFILES)/framework.make

-include GNUmakefile.postamble
