include $(GNUSTEP_MAKEFILES)/common.make

TOOL_NAME=	open

# The source files to be compiled
open_OBJC_FILES= \
	BBFileOpener.m \
	open.m

-include GNUmakefile.preamble
-include GNUmakefile.local

include $(GNUSTEP_MAKEFILES)/aggregate.make
include $(GNUSTEP_MAKEFILES)/tool.make

-include GNUmakefile.postamble
