all:
	sh $(CURDIR)/makefonts

install:
	sh $(CURDIR)/makefonts install

clean:
distclean:
	sh $(CURDIR)/makefonts clean

uninstall:
	sh $(CURDIR)/makefonts uninstall

.PHONY: all install clean distclean uninstall
