#! /bin/sh
cd `dirname $0`

# Check Autoconf version
ac=`which autoconf`
if test -n "$ac" ; then
	if test -x "$ac" ; then
		AC_VER=`autoconf --version | head -1 | sed 's/^[^0-9]*//'`
		AC_VER_MAJOR=`echo $AC_VER | cut -f1 -d'.'`
		AC_VER_MINOR=`echo $AC_VER | cut -f2 -d'.' | sed 's/[^0-9]*$//'`

		if test "$AC_VER_MAJOR" -lt "2" ; then
			errors="Autoconf 2.59 or greater needed to build configure.\n$errors"
		fi

		if test "$AC_VER_MAJOR" -eq "2" -a "$AC_VER_MINOR" -lt "59" ; then
			errors="Autoconf 2.59 or greater needed to build configure.\n$errors"
		fi
	fi
else
	errors="Autoconf not found. Backbone git requires autoconf to bootstrap itself.\n$errors"
fi

if test -n "$errors" ; then
	echo -e $errors
	exit 1
fi

autoheader && autoconf
