include $(GNUSTEP_MAKEFILES)/common.make

top_srcdir= $(shell pwd)

BBFRAMEWORKS= $(top_srcdir)/Frameworks
export BBFRAMEWORKS

SUBPROJECTS = \
	Frameworks/PrefsModule \
	\
	Applications/Preferences

include $(GNUSTEP_MAKEFILES)/aggregate.make
