include $(GNUSTEP_MAKEFILES)/common.make

BUNDLE_NAME=		Defaults
BUNDLE_EXTENSION=	.prefs
BUNDLE_INSTALL_DIR=	$(GNUSTEP_INSTALLATION_DIR)/Library/Preferences

Defaults_LANGUAGES= \
	English

Defaults_LOCALIZED_RESOURCE_FILES= \
	Defaults.gorm

Defaults_OBJC_FILES= \
	Defaults.m

Defaults_HEADERS= \
	Defaults.h

Defaults_PRINCIPAL_CLASS= \
	Defaults

-include GNUmakefile.preamble

include $(GNUSTEP_MAKEFILES)/bundle.make

-include GNUmakefile.postamble
